server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Handle Single Page Application routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Log configuring for easier debug
    error_log  /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;
}
